version: "3.9"
name: stockpile

services:
  backend:
    build: ./backend
    container_name: stockpile-backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend/data:/app/data
      - ./backend/qrcodes:/app/qrcodes
    restart: unless-stopped

  frontend:
    build: ./web
    container_name: stockpile-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
